### ISSUE TITLE
Create Slider Component

### ISSUE THREAD

**Issue by Leonardin96** [kelzenberg/master-project#69]
### Todo
For the interaction with the simulation we need a range-slider component which fulfills the following requirements
- [x] adjustable min and max values
- [x] react to input events
    - [x] create a json object with the new data (**only if the values changed**)
    - [x] send out value in relation to min-max values and scaling (linear or log)
- [x] show min, max and steps
- [x] fits the style language of the application  
- [x] change values to scientific (e.g. `1e-20`) notation if either min or max comes in this notation (should probably happen in the slider-controller)
- [x] only fire an event on `mouseup` (or equivalent event) and not `onchange`
